export const ADD_RECIPES = "ADD_RECIPES"
export const DELETE_RECIPE ="DELETE_RECIPE"
export const DELETE_ALL_RECIPES ="DELETE_ALL_RECIPES"


export const FETCH_RECIPES_IS_LOADING = "FETCH_RECIPES_IS_LOADING"
export const FETCH_RECIPES_SUCCESS= "FETCH_RECIPES_SUCCESS"
export const FETCH_RECIPES_ERROR= "FETCH_RECIPES_ERROR"